### ISSUE TITLE
What is the default value of "ds"?

### ISSUE THREAD

**Issue by kaneshin** [cubicdaiya/ngx_small_light#24]
Hi there.

I found the weird value for [Configuration#parameters](https://github.com/cubicdaiya/ngx_small_light/wiki/Configuration#parameters).

The  default value of the `"ds"` parameter is noted `'n'` just below;

| Parameter | Type | Default | Description |
| :---: | :---: | :----: | :--- |
| ds | char | n | destination scaling control |

However, there is no `'n'` on your [code](https://github.com/cubicdaiya/ngx_small_light/blob/master/src/ngx_http_small_light_size.c#L134) around the assignment of `"ds"`.

```c
/* get scaling option. */
prm_ds_str = NGX_HTTP_SMALL_LIGHT_PARAM_GET_LIT(&ctx->hash, "ds");
prm_ds     = prm_ds_str[0] ? prm_ds_str[0] : 'l';
if (prm_ds == 's' || (sz->dw < sz->sw - sz->sx) || (sz->dh < sz->sh - sz->sy)) {
    sz->scale_flg = 1;
} else {
```

It seems to me that the default value of `"ds"` is `'l'`.

Did I watch the wrong statement or file?

Please teach me where default value of `"ds"` is setting.

**Comment by cubicdaiya** [comment]
> Please teach me where default value of "ds" is setting.

The default value of `ds` is defined [here](https://github.com/cubicdaiya/ngx_small_light/blob/master/src/ngx_http_small_light_param.c#L45). So the default value of `ds` is always `n`. 

You can use 's' or 'n' for `ds`. 'l' is no longer used. Maybe the mistake inherited from `mod_small_light`. I'll fix in the near future. Thanks for your report.

On the other hand, `scale_flg` is often set 1 because `dw` and `dh` should be set smaller than `sw` and `sh` in the most cases.

**Comment by kaneshin** [comment]
I see. :cactus: 

> On the other hand, scale_flg is often set 1 because dw and dh should be set smaller than sw and sh in the most cases.

Good to know!
It'll be useful for me. Thanks!

**Comment by kaneshin** [comment]
Uh-oh, you need that is the issue still opened?

> You can use 's' or 'n' for ds. 'l' is no longer used. Maybe it is the mistake inherited from mod_small_light. I'll fix in the near future. Thanks for your report.

Please reopen if you need. thx
